### ISSUE TITLE
Bouvet Island region/continent

### ISSUE THREAD

**Issue by mrudden** [mikeprivette/only-flags#1]
Region and continent are currently defined as South America, but it appears to be closer to Cape Town, South Africa. I do not see a clear region definition for this location in ISO 3166. The CIA describes it as Antarctic Region and Wikipedia describes it as South Atlantic.

https://www.cia.gov/the-world-factbook/countries/bouvet-island/
https://en.wikipedia.org/wiki/Bouvet_Island

**Comment by mikeprivette** [comment]
This a confusing one as it appears to be a dependency of Norway but does not have a continent

**Comment by mikeprivette** [comment]
Updated based on the two links above
